import Head from "next/head";
import NextLink from "next/link";
import styles from "../styles/Home.module.css";
import { Text, Button, Spacer, Card } from "@nextui-org/react";

export default function Home() {
  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <section>
          <article>
            <h1>
              Create your own
              <span> last mile logistics </span>
              website and APP!
            </h1>
            <Text h2>We are Moover</Text>
            <Spacer />
            <p>
              lorem ipsum dolor sit amet consectetur adipisicing elit.lorem
              ipsum dolor sit amet consectetur adipisicing elit.lorem ipsum
              dolor sit amet consectetur adipisicing elit.lorem ipsum dolor sit
              amet consectetur adipisicing elit.
            </p>
            <Spacer />
            <NextLink href="/contact">
              <a>
                <Button color="gradient" shadow>
                  Get started
                </Button>
              </a>
            </NextLink>
          </article>
          <picture>
            <Card.Image
              objectFit="cover"
              width="100%"
              height="100%"
              src="https://i.pinimg.com/564x/37/9b/f4/379bf4980088d6f71f09a20fde2ce5d2.jpg"
            />
          </picture>
        </section>
      </div>
      <style jsx>{`
        section {
          width: 100%;
          height: 100%;
          display: flex;
        }
        article {
          width: 100%;
          flex-grow: 0;
        }
        h1 {
          font-size: 4rem;
          line-height: 4.25rem;
          max-width: 15ch;
        }
        h1 span {
          font-size: 72px;
          background: -webkit-linear-gradient(#7928caee, #f21361);
          -webkit-background-clip: text;
          -webkit-text-fill-color: transparent;
        }
        picture {
          display: none;
        }

        @media (min-width: 768px) {
          article {
            width: 70%;
          }
          picture {
            display: flex;
            position: relative;
            flex-grow: 1;
            max-width: 320px;
            width: 100%;
            transform: translate(25%, 5%);
          }
        }
        @media (min-width: 1024px) {
          article {
            width: 40%;
          }
          picture {
            max-width: 550px;
          }
        }
      `}</style>
    </>
  );
}
